### ISSUE TITLE
Page colors need to be consistent with zeplin mocks.

### ISSUE THREAD

**Issue by metzgerenator** [OpenMic/OpenMic---iOS#11]

**Comment by metzgerenator** [comment]
@adenaro I matched the rgb values.  Sometimes iOS interpretation of colors is different.  Also, it could be your screen resolution on the phone, vs what you see on the monitor.   I'll double check the rgb values, but just wanted to let you know.

**Comment by adenaro** [comment]
@metzgerenator Please double check that the rgb values are correct if they are we will have to come up with a strategy for replicating how the view looks on my monitor. Do you see the difference between the color values on your monitor and on your mobile device.
