### ISSUE TITLE
Change order of welcome screen.

### ISSUE THREAD

**Issue by metzgerenator** [OpenMic/OpenMic---iOS#15]

**Comment by adenaro** [comment]
@metzgerenator The welcome screen sequence should come after artist add and is in the sign up branch. Please review the flowchart. Therefore, the welcome sequence is ONLY visible to users who have signed up for the first time. https://docs.google.com/document/d/1JZk-VpCITwj5Ns_qFYFGvqnNv9cbkVi0GKqvQaffDB0/edit#heading=h.a7d3eg9g5gm2
