### ISSUE TITLE
Profile settings

### ISSUE THREAD

**Issue by adenaro** [OpenMic/OpenMic---iOS#67]
https://docs.google.com/document/d/1yON_n2nPdA87C3qKOj6PaGPQGuZBillLxRoVwSBVH48/edit#bookmark=id.ue7hcevziedr

The image below is the option view used on Instagram. The DESIGN and NAVIGATION implemented on our platform should similar. 

The Following settings should not be operational at the moment:
1.) Push Notifications
2.) Apple Pay
3.) Data policy
4.) All links under Legal
5.) Help Center

**Comment by adenaro** [comment]
![IMG_7241.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592f4dc01ed5621e68528d21/125516c66e82c728ace21e0d46c1b9bd1cd5d1fddeabf301b44fff9e2c4533317346f6292180bb2de7142c530e581dff41585e16affb8f7ff7b02e6c981e5ab38532022d8c6853beb2901eb70bbb258f4683b0b88e48c1e03b24f5c6.jpg)

**Comment by Eashir** [comment]
Slider in search radius setting

**Comment by adenaro** [comment]
The slider should look like this, but in the red color used on our platform.
![Screen Shot 2019-03-11 at 4.32.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592f4dc01ed5621e68528d21/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f26b7191a37cf111294f5d575ecc3c4a4356bcbbd671f3e57862804e0ebfd0385721ce3b16aee9854cec01ba21d91c87b0e8db4ad2f42f67b6d5db1063474f4dcbed5727a19141c95df349e24e53a0143466e3722431.png)

**Comment by adenaro** [comment]
Remember that the default is 50 miles so this should be reflected in the UI.

**Comment by adenaro** [comment]
Minimum 25 miles
