### ISSUE TITLE
The password “Show” button should toggle between Show And Hide.

### ISSUE THREAD

**Issue by metzgerenator** [OpenMic/OpenMic---iOS#7]

**Comment by metzgerenator** [comment]
I have this working can you let me know where you're having an issue, or provide a video of it not?

**Comment by adenaro** [comment]
The password reveals itself when "Show" is tapped but the WORD "Show" Should toggle to the word "HIDE" so that the user knows it can be tapped again to re-hide the password.

**Comment by metzgerenator** [comment]
This is done.  Let me know if the spacing is weird on other device sizes.
