### ISSUE TITLE
Need More Help button broken.

### ISSUE THREAD

**Issue by adenaro** [OpenMic/OpenMic---iOS#79]

**Comment by adenaro** [comment]
I'm getting this alert for some reason.
![Screen Shot 2019-03-14 at 11.42.36 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592f4dc01ed5621e68528d21/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f76b7191a379ee0c2f53415c48bc30254d58eeb9cb74fce36f34985619e8836c0a7c933517abbad318ec52ba208a1dd6b4bade1dc6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee34852ac12316ae67f356e0a.png)

**Comment by Eashir** [comment]
You'll have to use a real device since it uses a connected email account from the Mail app
