### ISSUE TITLE
“Or with e-mail” is missing line on the right and the left line is not the correct width.

### ISSUE THREAD

**Issue by metzgerenator** [OpenMic/OpenMic---iOS#8]

**Comment by adenaro** [comment]
The work package has been updated with an example with an example of Spotify using the lines on their sign up page.
https://docs.google.com/document/d/1JZk-VpCITwj5Ns_qFYFGvqnNv9cbkVi0GKqvQaffDB0/edit?usp=sharing

**Comment by metzgerenator** [comment]
@adenaro let me know if this looks ok on build 1.04
